# Copyright Statement:
#

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

local_path_full := $(shell pwd)/$(LOCAL_PATH)
btsdio_module_out_path := $(ANDROID_PRODUCT_OUT)$(BT_DRIVER_MODULE_PATH)
btsdio_module_target := $(btsdio_module_out_path)

#current parameter name for target arch on VSB is $(TARGET_ARCH)
ifeq ($(TARGET_KERNEL_ARCH),)
TARGET_KERNEL_ARCH := $(TARGET_ARCH)
endif

#avoid $(KERNEL_OUT)is not defined
ifeq ($(KERNEL_OUT),)
KERNEL_OUT := $(ANDROID_PRODUCT_OUT)/obj/KERNEL_OBJ
endif

LOCAL_MODULE := $(BT_DRIVER_MODULE_NAME)
LOCAL_MODULE_TAGS := optional
LOCAL_ADDITIONAL_DEPENDENCIES := $(btsdio_module_target)

include $(BUILD_PHONY_PACKAGE)

$(LOCAL_ADDITIONAL_DEPENDENCIES): PRIVATE_DRIVER_LOCAL_DIR := $(local_path_full)
$(LOCAL_ADDITIONAL_DEPENDENCIES): PRIVATE_DRIVER_OUT := $(btsdio_module_out_path)
$(LOCAL_ADDITIONAL_DEPENDENCIES): $(INSTALLED_KERNEL_TARGET)
	$(hide) rm -rf $(PRIVATE_DRIVER_OUT)
ifeq ($(MTK_I2S_PCM), true)
	$(MAKE) -C $(KERNEL_OUT) MTK_CHIP_PCM=TRUE M=$(PRIVATE_DRIVER_LOCAL_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) modules
	$(MAKE) -C $(KERNEL_OUT) MTK_CHIP_PCM=TRUE M=$(PRIVATE_DRIVER_LOCAL_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) modules INSTALL_MOD_PATH=$(ANDROID_PRODUCT_OUT)/obj/KERNEL_OBJ modules_install
else
	$(MAKE) -C $(KERNEL_OUT) M=$(PRIVATE_DRIVER_LOCAL_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) modules
	$(MAKE) -C $(KERNEL_OUT) M=$(PRIVATE_DRIVER_LOCAL_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) modules INSTALL_MOD_PATH=$(ANDROID_PRODUCT_OUT)/obj/KERNEL_OBJ modules_install
endif
	$(KERNEL_CROSS_COMPILE)strip -g $(PRIVATE_DRIVER_LOCAL_DIR)/$(BT_DRIVER_MODULE_NAME).ko
	$(hide) cp -f $(PRIVATE_DRIVER_LOCAL_DIR)/$(BT_DRIVER_MODULE_NAME).ko $(PRIVATE_DRIVER_OUT)
	$(MAKE) -C $(KERNEL_OUT) M=$(PRIVATE_DRIVER_LOCAL_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) clean

local_path_full :=
btsdio_module_out_path :=
btsdio_module_target :=
